CREATE TABLE Clients(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40)
);

CREATE TABLE Accounts(
    id INTEGER PRIMARY KEY,
    ClientId INTEGER,
    _money MONEY,
    FOREIGN KEY (ClientId) REFERENCES Clients (id)
);

CREATE TABLE card(
    id INTEGER PRIMARY KEY,
    AccountId INTEGER,
    code INTEGER,
    active BOOLEAN,
    FOREIGN KEY (AccountId) REFERENCES Accounts (id)
);

CREATE TABLE ATM(
    id INTEGER PRIMARY KEY,
    __array_length INTEGER,
    cash INTEGER[10],
    denomination INTEGER[10],
    addres VARCHAR(180)
);

GRANT SELECT, UPDATE ON TABLE ATM, card, Accounts TO atm_user;
